# Generated by Django 5.0.3 on 2024-03-26 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_name', models.CharField(max_length=255, null=True, verbose_name='File name')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight_data.flight')),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csv_name', models.CharField(max_length=255, null=True, verbose_name='File name')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight_data.flight')),
            ],
            options={
                'verbose_name': 'telemetry',
                'verbose_name_plural': 'telemetry',
            },
        ),
    ]
